/**
 * This class is generated by jOOQ
 */
package org.rankun.data;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>jooq_test</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<org.rankun.data.tables.records.TodoRecord, java.lang.Long> IDENTITY_TODO = Identities0.IDENTITY_TODO;
	public static final org.jooq.Identity<org.rankun.data.tables.records.TCityRecord, java.lang.Integer> IDENTITY_T_CITY = Identities0.IDENTITY_T_CITY;
	public static final org.jooq.Identity<org.rankun.data.tables.records.TCompanyRecord, org.jooq.types.UInteger> IDENTITY_T_COMPANY = Identities0.IDENTITY_T_COMPANY;
	public static final org.jooq.Identity<org.rankun.data.tables.records.TProvinceRecord, java.lang.Integer> IDENTITY_T_PROVINCE = Identities0.IDENTITY_T_PROVINCE;
	public static final org.jooq.Identity<org.rankun.data.tables.records.TRecruitmentRecord, org.jooq.types.UInteger> IDENTITY_T_RECRUITMENT = Identities0.IDENTITY_T_RECRUITMENT;
	public static final org.jooq.Identity<org.rankun.data.tables.records.TUserRecord, org.jooq.types.UInteger> IDENTITY_T_USER = Identities0.IDENTITY_T_USER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TodoRecord> KEY_TODO_PRIMARY = UniqueKeys0.KEY_TODO_PRIMARY;
	public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TCityRecord> KEY_T_CITY_PRIMARY = UniqueKeys0.KEY_T_CITY_PRIMARY;
	public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TCompanyRecord> KEY_T_COMPANY_PRIMARY = UniqueKeys0.KEY_T_COMPANY_PRIMARY;
	public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TProvinceRecord> KEY_T_PROVINCE_PRIMARY = UniqueKeys0.KEY_T_PROVINCE_PRIMARY;
	public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TRecruitmentRecord> KEY_T_RECRUITMENT_PRIMARY = UniqueKeys0.KEY_T_RECRUITMENT_PRIMARY;
	public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TSchoolRecord> KEY_T_SCHOOL_PRIMARY = UniqueKeys0.KEY_T_SCHOOL_PRIMARY;
	public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TUserRecord> KEY_T_USER_PRIMARY = UniqueKeys0.KEY_T_USER_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<org.rankun.data.tables.records.TSchoolRecord, org.rankun.data.tables.records.TProvinceRecord> FK_SCHOOL_PROVINCE = ForeignKeys0.FK_SCHOOL_PROVINCE;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<org.rankun.data.tables.records.TodoRecord, java.lang.Long> IDENTITY_TODO = createIdentity(org.rankun.data.tables.Todo.TODO, org.rankun.data.tables.Todo.TODO.ID);
		public static org.jooq.Identity<org.rankun.data.tables.records.TCityRecord, java.lang.Integer> IDENTITY_T_CITY = createIdentity(org.rankun.data.tables.TCity.T_CITY, org.rankun.data.tables.TCity.T_CITY.ID);
		public static org.jooq.Identity<org.rankun.data.tables.records.TCompanyRecord, org.jooq.types.UInteger> IDENTITY_T_COMPANY = createIdentity(org.rankun.data.tables.TCompany.T_COMPANY, org.rankun.data.tables.TCompany.T_COMPANY.CID);
		public static org.jooq.Identity<org.rankun.data.tables.records.TProvinceRecord, java.lang.Integer> IDENTITY_T_PROVINCE = createIdentity(org.rankun.data.tables.TProvince.T_PROVINCE, org.rankun.data.tables.TProvince.T_PROVINCE.ID);
		public static org.jooq.Identity<org.rankun.data.tables.records.TRecruitmentRecord, org.jooq.types.UInteger> IDENTITY_T_RECRUITMENT = createIdentity(org.rankun.data.tables.TRecruitment.T_RECRUITMENT, org.rankun.data.tables.TRecruitment.T_RECRUITMENT.RID);
		public static org.jooq.Identity<org.rankun.data.tables.records.TUserRecord, org.jooq.types.UInteger> IDENTITY_T_USER = createIdentity(org.rankun.data.tables.TUser.T_USER, org.rankun.data.tables.TUser.T_USER.UID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TodoRecord> KEY_TODO_PRIMARY = createUniqueKey(org.rankun.data.tables.Todo.TODO, org.rankun.data.tables.Todo.TODO.ID);
		public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TCityRecord> KEY_T_CITY_PRIMARY = createUniqueKey(org.rankun.data.tables.TCity.T_CITY, org.rankun.data.tables.TCity.T_CITY.ID);
		public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TCompanyRecord> KEY_T_COMPANY_PRIMARY = createUniqueKey(org.rankun.data.tables.TCompany.T_COMPANY, org.rankun.data.tables.TCompany.T_COMPANY.CID);
		public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TProvinceRecord> KEY_T_PROVINCE_PRIMARY = createUniqueKey(org.rankun.data.tables.TProvince.T_PROVINCE, org.rankun.data.tables.TProvince.T_PROVINCE.ID);
		public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TRecruitmentRecord> KEY_T_RECRUITMENT_PRIMARY = createUniqueKey(org.rankun.data.tables.TRecruitment.T_RECRUITMENT, org.rankun.data.tables.TRecruitment.T_RECRUITMENT.RID);
		public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TSchoolRecord> KEY_T_SCHOOL_PRIMARY = createUniqueKey(org.rankun.data.tables.TSchool.T_SCHOOL, org.rankun.data.tables.TSchool.T_SCHOOL.ID);
		public static final org.jooq.UniqueKey<org.rankun.data.tables.records.TUserRecord> KEY_T_USER_PRIMARY = createUniqueKey(org.rankun.data.tables.TUser.T_USER, org.rankun.data.tables.TUser.T_USER.UID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<org.rankun.data.tables.records.TSchoolRecord, org.rankun.data.tables.records.TProvinceRecord> FK_SCHOOL_PROVINCE = createForeignKey(org.rankun.data.Keys.KEY_T_PROVINCE_PRIMARY, org.rankun.data.tables.TSchool.T_SCHOOL, org.rankun.data.tables.TSchool.T_SCHOOL.PROVINCE);
	}
}
