/**
 * This class is generated by jOOQ
 */
package org.rankun.data;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in jooq_test
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table jooq_test.todo
	 */
	public static final org.rankun.data.tables.Todo TODO = org.rankun.data.tables.Todo.TODO;

	/**
	 * The table jooq_test.t_city
	 */
	public static final org.rankun.data.tables.TCity T_CITY = org.rankun.data.tables.TCity.T_CITY;

	/**
	 * The table jooq_test.t_company
	 */
	public static final org.rankun.data.tables.TCompany T_COMPANY = org.rankun.data.tables.TCompany.T_COMPANY;

	/**
	 * 省
	 */
	public static final org.rankun.data.tables.TProvince T_PROVINCE = org.rankun.data.tables.TProvince.T_PROVINCE;

	/**
	 * The table jooq_test.t_recruitment
	 */
	public static final org.rankun.data.tables.TRecruitment T_RECRUITMENT = org.rankun.data.tables.TRecruitment.T_RECRUITMENT;

	/**
	 * 学校

一个有独立教务管理的就是一个学校

用不同教务管理的不是同一个学校
	 */
	public static final org.rankun.data.tables.TSchool T_SCHOOL = org.rankun.data.tables.TSchool.T_SCHOOL;

	/**
	 * The table jooq_test.t_user
	 */
	public static final org.rankun.data.tables.TUser T_USER = org.rankun.data.tables.TUser.T_USER;
}
