/**
 * This class is generated by jOOQ
 */
package org.rankun.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TodoRecord extends org.jooq.impl.UpdatableRecordImpl<org.rankun.data.tables.records.TodoRecord> implements org.jooq.Record5<java.lang.Long, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = 2051916059;

	/**
	 * Setter for <code>jooq_test.todo.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jooq_test.todo.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>jooq_test.todo.creation_time</code>.
	 */
	public void setCreationTime(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jooq_test.todo.creation_time</code>.
	 */
	public java.sql.Timestamp getCreationTime() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>jooq_test.todo.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jooq_test.todo.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>jooq_test.todo.modification_time</code>.
	 */
	public void setModificationTime(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>jooq_test.todo.modification_time</code>.
	 */
	public java.sql.Timestamp getModificationTime() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>jooq_test.todo.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>jooq_test.todo.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.rankun.data.tables.Todo.TODO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return org.rankun.data.tables.Todo.TODO.CREATION_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.rankun.data.tables.Todo.TODO.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return org.rankun.data.tables.Todo.TODO.MODIFICATION_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.rankun.data.tables.Todo.TODO.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getCreationTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getModificationTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TodoRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TodoRecord value2(java.sql.Timestamp value) {
		setCreationTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TodoRecord value3(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TodoRecord value4(java.sql.Timestamp value) {
		setModificationTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TodoRecord value5(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TodoRecord values(java.lang.Long value1, java.sql.Timestamp value2, java.lang.String value3, java.sql.Timestamp value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TodoRecord
	 */
	public TodoRecord() {
		super(org.rankun.data.tables.Todo.TODO);
	}

	/**
	 * Create a detached, initialised TodoRecord
	 */
	public TodoRecord(java.lang.Long id, java.sql.Timestamp creationTime, java.lang.String description, java.sql.Timestamp modificationTime, java.lang.String title) {
		super(org.rankun.data.tables.Todo.TODO);

		setValue(0, id);
		setValue(1, creationTime);
		setValue(2, description);
		setValue(3, modificationTime);
		setValue(4, title);
	}
}
