/**
 * This class is generated by jOOQ
 */
package org.rankun.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRecruitmentRecord extends org.jooq.impl.UpdatableRecordImpl<org.rankun.data.tables.records.TRecruitmentRecord> implements org.jooq.Record7<org.jooq.types.UInteger, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 1525761722;

	/**
	 * Setter for <code>jooq_test.t_recruitment.rid</code>.
	 */
	public void setRid(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jooq_test.t_recruitment.rid</code>.
	 */
	public org.jooq.types.UInteger getRid() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>jooq_test.t_recruitment.showTime</code>.
	 */
	public void setShowtime(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jooq_test.t_recruitment.showTime</code>.
	 */
	public java.sql.Timestamp getShowtime() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>jooq_test.t_recruitment.school</code>.
	 */
	public void setSchool(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jooq_test.t_recruitment.school</code>.
	 */
	public java.lang.Integer getSchool() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>jooq_test.t_recruitment.place</code>.
	 */
	public void setPlace(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>jooq_test.t_recruitment.place</code>.
	 */
	public java.lang.String getPlace() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>jooq_test.t_recruitment.company</code>.
	 */
	public void setCompany(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>jooq_test.t_recruitment.company</code>.
	 */
	public java.lang.Integer getCompany() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>jooq_test.t_recruitment.jobType</code>.
	 */
	public void setJobtype(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>jooq_test.t_recruitment.jobType</code>.
	 */
	public java.lang.Integer getJobtype() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>jooq_test.t_recruitment.content</code>. 招聘信息, 内容, 一大篇文本, HTML
	 */
	public void setContent(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>jooq_test.t_recruitment.content</code>. 招聘信息, 内容, 一大篇文本, HTML
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<org.jooq.types.UInteger, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<org.jooq.types.UInteger, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return org.rankun.data.tables.TRecruitment.T_RECRUITMENT.RID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return org.rankun.data.tables.TRecruitment.T_RECRUITMENT.SHOWTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return org.rankun.data.tables.TRecruitment.T_RECRUITMENT.SCHOOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.rankun.data.tables.TRecruitment.T_RECRUITMENT.PLACE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return org.rankun.data.tables.TRecruitment.T_RECRUITMENT.COMPANY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return org.rankun.data.tables.TRecruitment.T_RECRUITMENT.JOBTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return org.rankun.data.tables.TRecruitment.T_RECRUITMENT.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getRid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getShowtime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getSchool();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPlace();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getCompany();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getJobtype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TRecruitmentRecord value1(org.jooq.types.UInteger value) {
		setRid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TRecruitmentRecord value2(java.sql.Timestamp value) {
		setShowtime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TRecruitmentRecord value3(java.lang.Integer value) {
		setSchool(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TRecruitmentRecord value4(java.lang.String value) {
		setPlace(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TRecruitmentRecord value5(java.lang.Integer value) {
		setCompany(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TRecruitmentRecord value6(java.lang.Integer value) {
		setJobtype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TRecruitmentRecord value7(java.lang.String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TRecruitmentRecord values(org.jooq.types.UInteger value1, java.sql.Timestamp value2, java.lang.Integer value3, java.lang.String value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TRecruitmentRecord
	 */
	public TRecruitmentRecord() {
		super(org.rankun.data.tables.TRecruitment.T_RECRUITMENT);
	}

	/**
	 * Create a detached, initialised TRecruitmentRecord
	 */
	public TRecruitmentRecord(org.jooq.types.UInteger rid, java.sql.Timestamp showtime, java.lang.Integer school, java.lang.String place, java.lang.Integer company, java.lang.Integer jobtype, java.lang.String content) {
		super(org.rankun.data.tables.TRecruitment.T_RECRUITMENT);

		setValue(0, rid);
		setValue(1, showtime);
		setValue(2, school);
		setValue(3, place);
		setValue(4, company);
		setValue(5, jobtype);
		setValue(6, content);
	}
}
