/**
 * This class is generated by jOOQ
 */
package org.rankun.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRecord extends org.jooq.impl.UpdatableRecordImpl<org.rankun.data.tables.records.TUserRecord> implements org.jooq.Record10<org.jooq.types.UInteger, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = -656583315;

	/**
	 * Setter for <code>jooq_test.t_user.uid</code>.
	 */
	public void setUid(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jooq_test.t_user.uid</code>.
	 */
	public org.jooq.types.UInteger getUid() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>jooq_test.t_user.userName</code>.
	 */
	public void setUsername(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jooq_test.t_user.userName</code>.
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>jooq_test.t_user.password</code>.
	 */
	public void setPassword(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jooq_test.t_user.password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>jooq_test.t_user.gender</code>.
	 */
	public void setGender(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>jooq_test.t_user.gender</code>.
	 */
	public java.lang.Integer getGender() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>jooq_test.t_user.nickName</code>.
	 */
	public void setNickname(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>jooq_test.t_user.nickName</code>.
	 */
	public java.lang.String getNickname() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>jooq_test.t_user.avatar</code>.
	 */
	public void setAvatar(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>jooq_test.t_user.avatar</code>.
	 */
	public java.lang.String getAvatar() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>jooq_test.t_user.sign</code>.
	 */
	public void setSign(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>jooq_test.t_user.sign</code>.
	 */
	public java.lang.String getSign() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>jooq_test.t_user.school</code>.
	 */
	public void setSchool(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>jooq_test.t_user.school</code>.
	 */
	public java.lang.Integer getSchool() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>jooq_test.t_user.register</code>.
	 */
	public void setRegister(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>jooq_test.t_user.register</code>.
	 */
	public java.sql.Timestamp getRegister() {
		return (java.sql.Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>jooq_test.t_user.location</code>.
	 */
	public void setLocation(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>jooq_test.t_user.location</code>.
	 */
	public java.lang.String getLocation() {
		return (java.lang.String) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<org.jooq.types.UInteger, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<org.jooq.types.UInteger, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return org.rankun.data.tables.TUser.T_USER.UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.rankun.data.tables.TUser.T_USER.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.rankun.data.tables.TUser.T_USER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return org.rankun.data.tables.TUser.T_USER.GENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.rankun.data.tables.TUser.T_USER.NICKNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return org.rankun.data.tables.TUser.T_USER.AVATAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return org.rankun.data.tables.TUser.T_USER.SIGN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return org.rankun.data.tables.TUser.T_USER.SCHOOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return org.rankun.data.tables.TUser.T_USER.REGISTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return org.rankun.data.tables.TUser.T_USER.LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getGender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getNickname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getAvatar();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getSign();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getSchool();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getRegister();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value1(org.jooq.types.UInteger value) {
		setUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value2(java.lang.String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value3(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value4(java.lang.Integer value) {
		setGender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value5(java.lang.String value) {
		setNickname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value6(java.lang.String value) {
		setAvatar(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value7(java.lang.String value) {
		setSign(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value8(java.lang.Integer value) {
		setSchool(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value9(java.sql.Timestamp value) {
		setRegister(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord value10(java.lang.String value) {
		setLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TUserRecord values(org.jooq.types.UInteger value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.Integer value8, java.sql.Timestamp value9, java.lang.String value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TUserRecord
	 */
	public TUserRecord() {
		super(org.rankun.data.tables.TUser.T_USER);
	}

	/**
	 * Create a detached, initialised TUserRecord
	 */
	public TUserRecord(org.jooq.types.UInteger uid, java.lang.String username, java.lang.String password, java.lang.Integer gender, java.lang.String nickname, java.lang.String avatar, java.lang.String sign, java.lang.Integer school, java.sql.Timestamp register, java.lang.String location) {
		super(org.rankun.data.tables.TUser.T_USER);

		setValue(0, uid);
		setValue(1, username);
		setValue(2, password);
		setValue(3, gender);
		setValue(4, nickname);
		setValue(5, avatar);
		setValue(6, sign);
		setValue(7, school);
		setValue(8, register);
		setValue(9, location);
	}
}
