/**
 * This class is generated by jOOQ
 */
package org.rankun.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCompany extends org.jooq.impl.TableImpl<org.rankun.data.tables.records.TCompanyRecord> {

	private static final long serialVersionUID = 767693439;

	/**
	 * The singleton instance of <code>jooq_test.t_company</code>
	 */
	public static final org.rankun.data.tables.TCompany T_COMPANY = new org.rankun.data.tables.TCompany();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rankun.data.tables.records.TCompanyRecord> getRecordType() {
		return org.rankun.data.tables.records.TCompanyRecord.class;
	}

	/**
	 * The column <code>jooq_test.t_company.cid</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TCompanyRecord, org.jooq.types.UInteger> CID = createField("cid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jooq_test.t_company.name</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TCompanyRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(256).defaulted(true), this, "");

	/**
	 * Create a <code>jooq_test.t_company</code> table reference
	 */
	public TCompany() {
		this("t_company", null);
	}

	/**
	 * Create an aliased <code>jooq_test.t_company</code> table reference
	 */
	public TCompany(java.lang.String alias) {
		this(alias, org.rankun.data.tables.TCompany.T_COMPANY);
	}

	private TCompany(java.lang.String alias, org.jooq.Table<org.rankun.data.tables.records.TCompanyRecord> aliased) {
		this(alias, aliased, null);
	}

	private TCompany(java.lang.String alias, org.jooq.Table<org.rankun.data.tables.records.TCompanyRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.rankun.data.JooqTest.JOOQ_TEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rankun.data.tables.records.TCompanyRecord, org.jooq.types.UInteger> getIdentity() {
		return org.rankun.data.Keys.IDENTITY_T_COMPANY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rankun.data.tables.records.TCompanyRecord> getPrimaryKey() {
		return org.rankun.data.Keys.KEY_T_COMPANY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rankun.data.tables.records.TCompanyRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rankun.data.tables.records.TCompanyRecord>>asList(org.rankun.data.Keys.KEY_T_COMPANY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rankun.data.tables.TCompany as(java.lang.String alias) {
		return new org.rankun.data.tables.TCompany(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.rankun.data.tables.TCompany rename(java.lang.String name) {
		return new org.rankun.data.tables.TCompany(name, null);
	}
}
