/**
 * This class is generated by jOOQ
 */
package org.rankun.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Todo extends org.jooq.impl.TableImpl<org.rankun.data.tables.records.TodoRecord> {

	private static final long serialVersionUID = 293277311;

	/**
	 * The singleton instance of <code>jooq_test.todo</code>
	 */
	public static final org.rankun.data.tables.Todo TODO = new org.rankun.data.tables.Todo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rankun.data.tables.records.TodoRecord> getRecordType() {
		return org.rankun.data.tables.records.TodoRecord.class;
	}

	/**
	 * The column <code>jooq_test.todo.id</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TodoRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>jooq_test.todo.creation_time</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TodoRecord, java.sql.Timestamp> CREATION_TIME = createField("creation_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>jooq_test.todo.description</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TodoRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>jooq_test.todo.modification_time</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TodoRecord, java.sql.Timestamp> MODIFICATION_TIME = createField("modification_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>jooq_test.todo.title</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TodoRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>jooq_test.todo</code> table reference
	 */
	public Todo() {
		this("todo", null);
	}

	/**
	 * Create an aliased <code>jooq_test.todo</code> table reference
	 */
	public Todo(java.lang.String alias) {
		this(alias, org.rankun.data.tables.Todo.TODO);
	}

	private Todo(java.lang.String alias, org.jooq.Table<org.rankun.data.tables.records.TodoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Todo(java.lang.String alias, org.jooq.Table<org.rankun.data.tables.records.TodoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.rankun.data.JooqTest.JOOQ_TEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rankun.data.tables.records.TodoRecord, java.lang.Long> getIdentity() {
		return org.rankun.data.Keys.IDENTITY_TODO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rankun.data.tables.records.TodoRecord> getPrimaryKey() {
		return org.rankun.data.Keys.KEY_TODO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rankun.data.tables.records.TodoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rankun.data.tables.records.TodoRecord>>asList(org.rankun.data.Keys.KEY_TODO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rankun.data.tables.Todo as(java.lang.String alias) {
		return new org.rankun.data.tables.Todo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.rankun.data.tables.Todo rename(java.lang.String name) {
		return new org.rankun.data.tables.Todo(name, null);
	}
}
