/**
 * This class is generated by jOOQ
 */
package org.rankun.data.tables;

/**
 * This class is generated by jOOQ.
 *
 * 省
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TProvince extends org.jooq.impl.TableImpl<org.rankun.data.tables.records.TProvinceRecord> {

	private static final long serialVersionUID = -2073733686;

	/**
	 * The singleton instance of <code>jooq_test.t_province</code>
	 */
	public static final org.rankun.data.tables.TProvince T_PROVINCE = new org.rankun.data.tables.TProvince();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rankun.data.tables.records.TProvinceRecord> getRecordType() {
		return org.rankun.data.tables.records.TProvinceRecord.class;
	}

	/**
	 * The column <code>jooq_test.t_province.id</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TProvinceRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>jooq_test.t_province.name</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TProvinceRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>jooq_test.t_province</code> table reference
	 */
	public TProvince() {
		this("t_province", null);
	}

	/**
	 * Create an aliased <code>jooq_test.t_province</code> table reference
	 */
	public TProvince(java.lang.String alias) {
		this(alias, org.rankun.data.tables.TProvince.T_PROVINCE);
	}

	private TProvince(java.lang.String alias, org.jooq.Table<org.rankun.data.tables.records.TProvinceRecord> aliased) {
		this(alias, aliased, null);
	}

	private TProvince(java.lang.String alias, org.jooq.Table<org.rankun.data.tables.records.TProvinceRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.rankun.data.JooqTest.JOOQ_TEST, aliased, parameters, "省");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rankun.data.tables.records.TProvinceRecord, java.lang.Integer> getIdentity() {
		return org.rankun.data.Keys.IDENTITY_T_PROVINCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rankun.data.tables.records.TProvinceRecord> getPrimaryKey() {
		return org.rankun.data.Keys.KEY_T_PROVINCE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rankun.data.tables.records.TProvinceRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rankun.data.tables.records.TProvinceRecord>>asList(org.rankun.data.Keys.KEY_T_PROVINCE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rankun.data.tables.TProvince as(java.lang.String alias) {
		return new org.rankun.data.tables.TProvince(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.rankun.data.tables.TProvince rename(java.lang.String name) {
		return new org.rankun.data.tables.TProvince(name, null);
	}
}
