/**
 * This class is generated by jOOQ
 */
package org.rankun.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRecruitment extends org.jooq.impl.TableImpl<org.rankun.data.tables.records.TRecruitmentRecord> {

	private static final long serialVersionUID = -1652707701;

	/**
	 * The singleton instance of <code>jooq_test.t_recruitment</code>
	 */
	public static final org.rankun.data.tables.TRecruitment T_RECRUITMENT = new org.rankun.data.tables.TRecruitment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rankun.data.tables.records.TRecruitmentRecord> getRecordType() {
		return org.rankun.data.tables.records.TRecruitmentRecord.class;
	}

	/**
	 * The column <code>jooq_test.t_recruitment.rid</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TRecruitmentRecord, org.jooq.types.UInteger> RID = createField("rid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jooq_test.t_recruitment.showTime</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TRecruitmentRecord, java.sql.Timestamp> SHOWTIME = createField("showTime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>jooq_test.t_recruitment.school</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TRecruitmentRecord, java.lang.Integer> SCHOOL = createField("school", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>jooq_test.t_recruitment.place</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TRecruitmentRecord, java.lang.String> PLACE = createField("place", org.jooq.impl.SQLDataType.VARCHAR.length(512), this, "");

	/**
	 * The column <code>jooq_test.t_recruitment.company</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TRecruitmentRecord, java.lang.Integer> COMPANY = createField("company", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>jooq_test.t_recruitment.jobType</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TRecruitmentRecord, java.lang.Integer> JOBTYPE = createField("jobType", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>jooq_test.t_recruitment.content</code>. 招聘信息, 内容, 一大篇文本, HTML
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TRecruitmentRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB.length(16777215), this, "招聘信息, 内容, 一大篇文本, HTML");

	/**
	 * Create a <code>jooq_test.t_recruitment</code> table reference
	 */
	public TRecruitment() {
		this("t_recruitment", null);
	}

	/**
	 * Create an aliased <code>jooq_test.t_recruitment</code> table reference
	 */
	public TRecruitment(java.lang.String alias) {
		this(alias, org.rankun.data.tables.TRecruitment.T_RECRUITMENT);
	}

	private TRecruitment(java.lang.String alias, org.jooq.Table<org.rankun.data.tables.records.TRecruitmentRecord> aliased) {
		this(alias, aliased, null);
	}

	private TRecruitment(java.lang.String alias, org.jooq.Table<org.rankun.data.tables.records.TRecruitmentRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.rankun.data.JooqTest.JOOQ_TEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rankun.data.tables.records.TRecruitmentRecord, org.jooq.types.UInteger> getIdentity() {
		return org.rankun.data.Keys.IDENTITY_T_RECRUITMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rankun.data.tables.records.TRecruitmentRecord> getPrimaryKey() {
		return org.rankun.data.Keys.KEY_T_RECRUITMENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rankun.data.tables.records.TRecruitmentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rankun.data.tables.records.TRecruitmentRecord>>asList(org.rankun.data.Keys.KEY_T_RECRUITMENT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rankun.data.tables.TRecruitment as(java.lang.String alias) {
		return new org.rankun.data.tables.TRecruitment(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.rankun.data.tables.TRecruitment rename(java.lang.String name) {
		return new org.rankun.data.tables.TRecruitment(name, null);
	}
}
