/**
 * This class is generated by jOOQ
 */
package org.rankun.data.tables;

/**
 * This class is generated by jOOQ.
 *
 * 学校
 * 
 * 一个有独立教务管理的就是一个学校
 * 
 * 用不同教务管理的不是同一个学校
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TSchool extends org.jooq.impl.TableImpl<org.rankun.data.tables.records.TSchoolRecord> {

	private static final long serialVersionUID = 925456825;

	/**
	 * The singleton instance of <code>jooq_test.t_school</code>
	 */
	public static final org.rankun.data.tables.TSchool T_SCHOOL = new org.rankun.data.tables.TSchool();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rankun.data.tables.records.TSchoolRecord> getRecordType() {
		return org.rankun.data.tables.records.TSchoolRecord.class;
	}

	/**
	 * The column <code>jooq_test.t_school.id</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TSchoolRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>jooq_test.t_school.name</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TSchoolRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>jooq_test.t_school.province</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TSchoolRecord, java.lang.Integer> PROVINCE = createField("province", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>jooq_test.t_school</code> table reference
	 */
	public TSchool() {
		this("t_school", null);
	}

	/**
	 * Create an aliased <code>jooq_test.t_school</code> table reference
	 */
	public TSchool(java.lang.String alias) {
		this(alias, org.rankun.data.tables.TSchool.T_SCHOOL);
	}

	private TSchool(java.lang.String alias, org.jooq.Table<org.rankun.data.tables.records.TSchoolRecord> aliased) {
		this(alias, aliased, null);
	}

	private TSchool(java.lang.String alias, org.jooq.Table<org.rankun.data.tables.records.TSchoolRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.rankun.data.JooqTest.JOOQ_TEST, aliased, parameters, "学校\n\n一个有独立教务管理的就是一个学校\n\n用不同教务管理的不是同一个学校");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rankun.data.tables.records.TSchoolRecord> getPrimaryKey() {
		return org.rankun.data.Keys.KEY_T_SCHOOL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rankun.data.tables.records.TSchoolRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rankun.data.tables.records.TSchoolRecord>>asList(org.rankun.data.Keys.KEY_T_SCHOOL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.rankun.data.tables.records.TSchoolRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.rankun.data.tables.records.TSchoolRecord, ?>>asList(org.rankun.data.Keys.FK_SCHOOL_PROVINCE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rankun.data.tables.TSchool as(java.lang.String alias) {
		return new org.rankun.data.tables.TSchool(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.rankun.data.tables.TSchool rename(java.lang.String name) {
		return new org.rankun.data.tables.TSchool(name, null);
	}
}
