/**
 * This class is generated by jOOQ
 */
package org.rankun.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUser extends org.jooq.impl.TableImpl<org.rankun.data.tables.records.TUserRecord> {

	private static final long serialVersionUID = 1457437680;

	/**
	 * The singleton instance of <code>jooq_test.t_user</code>
	 */
	public static final org.rankun.data.tables.TUser T_USER = new org.rankun.data.tables.TUser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rankun.data.tables.records.TUserRecord> getRecordType() {
		return org.rankun.data.tables.records.TUserRecord.class;
	}

	/**
	 * The column <code>jooq_test.t_user.uid</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TUserRecord, org.jooq.types.UInteger> UID = createField("uid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jooq_test.t_user.userName</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TUserRecord, java.lang.String> USERNAME = createField("userName", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>jooq_test.t_user.password</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TUserRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>jooq_test.t_user.gender</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TUserRecord, java.lang.Integer> GENDER = createField("gender", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>jooq_test.t_user.nickName</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TUserRecord, java.lang.String> NICKNAME = createField("nickName", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>jooq_test.t_user.avatar</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TUserRecord, java.lang.String> AVATAR = createField("avatar", org.jooq.impl.SQLDataType.VARCHAR.length(512), this, "");

	/**
	 * The column <code>jooq_test.t_user.sign</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TUserRecord, java.lang.String> SIGN = createField("sign", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>jooq_test.t_user.school</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TUserRecord, java.lang.Integer> SCHOOL = createField("school", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>jooq_test.t_user.register</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TUserRecord, java.sql.Timestamp> REGISTER = createField("register", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>jooq_test.t_user.location</code>.
	 */
	public final org.jooq.TableField<org.rankun.data.tables.records.TUserRecord, java.lang.String> LOCATION = createField("location", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * Create a <code>jooq_test.t_user</code> table reference
	 */
	public TUser() {
		this("t_user", null);
	}

	/**
	 * Create an aliased <code>jooq_test.t_user</code> table reference
	 */
	public TUser(java.lang.String alias) {
		this(alias, org.rankun.data.tables.TUser.T_USER);
	}

	private TUser(java.lang.String alias, org.jooq.Table<org.rankun.data.tables.records.TUserRecord> aliased) {
		this(alias, aliased, null);
	}

	private TUser(java.lang.String alias, org.jooq.Table<org.rankun.data.tables.records.TUserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.rankun.data.JooqTest.JOOQ_TEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rankun.data.tables.records.TUserRecord, org.jooq.types.UInteger> getIdentity() {
		return org.rankun.data.Keys.IDENTITY_T_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rankun.data.tables.records.TUserRecord> getPrimaryKey() {
		return org.rankun.data.Keys.KEY_T_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rankun.data.tables.records.TUserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rankun.data.tables.records.TUserRecord>>asList(org.rankun.data.Keys.KEY_T_USER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rankun.data.tables.TUser as(java.lang.String alias) {
		return new org.rankun.data.tables.TUser(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.rankun.data.tables.TUser rename(java.lang.String name) {
		return new org.rankun.data.tables.TUser(name, null);
	}
}
